# This file was generated by GoReleaser. DO NOT EDIT.
class Azuretoastd < Formula
  desc "Service that populates information associated with Azure daily usage."
  homepage "https://github.com/mobingi/ouchantools"
  version "1.0.44"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.44/ouchantools_1.0.44_darwin_amd64.tar.gz"
    sha256 "04afc1f92e95223e75bc8a9a64f75da9d20ee98beb2de6d45b4a9da9391f9cb3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.44/ouchantools_1.0.44_linux_amd64.tar.gz"
    sha256 "6d5e6ad7cdfbdd4c97b3c7cdac5807146dad8856b326e6d3a57169caf916d2e4"
  end

  def install
    bin.install "azuretoastd"
  end

  test do
    assert_match /Service that populates information associated with Azure daily usage/, shell_output("#{bin}/azuretoastd -h", 0)
  end
end
