# This file was generated by GoReleaser. DO NOT EDIT.
class Azurebatchd < Formula
  desc "Batch binary for Ripple/Wave for Azure."
  homepage "https://github.com/mobingi/ouchantools"
  version "1.0.37"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.37/ouchantools_1.0.37_darwin_amd64.tar.gz"
    sha256 "111ac45f3cc971ce930a26733b0a3281f77b8752c56395257e8f79604928b982"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mobingi/ouchantools/releases/download/v1.0.37/ouchantools_1.0.37_linux_amd64.tar.gz"
      sha256 "29882901cef4a4c63cc3abdca651f56e3854ee2d6dd74d48626534d69bfb4268"
    end
  end

  def install
    bin.install "azurebatchd"
  end

  test do
    assert_match /Wave/, shell_output("#{bin}/azurebatchd -h", 0)
  end
end
