# This file was generated by GoReleaser. DO NOT EDIT.
class Azureridard < Formula
  desc "Service that detects new, updated and deleted RI for Azure."
  homepage "https://github.com/mobingi/ouchantools"
  version "1.0.36"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.36/ouchantools_1.0.36_darwin_amd64.tar.gz"
    sha256 "ae2759df378f2bbc346dab52cc33ad6255778f89a449ee75aa807e09635fb565"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mobingi/ouchantools/releases/download/v1.0.36/ouchantools_1.0.36_linux_amd64.tar.gz"
      sha256 "dfb7f5a2c5860ecb494bb96e37b08062ea30653180826b2892a4566b5c75b77a"
    end
  end

  def install
    bin.install "azureridard"
  end

  test do
    assert_match /Service that detects new, updated and deleted RI for Azure/, shell_output("#{bin}/azureridard -h", 0)
  end
end
