# This file was generated by GoReleaser. DO NOT EDIT.
class Azurecustomerd < Formula
  desc "Manage Azure customer mapping, status and naming in Azure."
  homepage "https://github.com/mobingi/ouchantools"
  version "1.0.47"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.47/ouchantools_1.0.47_darwin_amd64.tar.gz"
    sha256 "9f2ad62c984fc488b6853276d6145d096de1e125d82b81ab5a84cbcb4e1a8691"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.47/ouchantools_1.0.47_linux_amd64.tar.gz"
    sha256 "1b730d87524e34e5928e8fe474ecd26e08555a267a061272729829c643e62d97"
  end

  def install
    bin.install "azurecustomerd"
  end

  test do
    assert_match /Manage Azure customer mapping, status and naming in Azure/, shell_output("#{bin}/azurecustomerd -h", 0)
  end
end
