# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bluectl < Formula
  desc "The official command line interface for Alphaus services."
  homepage "https://github.com/alphauslabs/bluectl"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/alphauslabs/bluectl/releases/download/v0.0.2/bluectl_0.0.2_darwin_amd64.tar.gz"
    sha256 "d4925c9f8e83cf8f2683b6281ec7063f0c52bfd858d86bd08a0bf957b147a130"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/alphauslabs/bluectl/releases/download/v0.0.2/bluectl_0.0.2_linux_amd64.tar.gz"
    sha256 "479c0827d4fe59623d0a25c3a32b52b7a4b64991944e87d3a44c73701060f4f5"
  end

  def install
    bin.install "bluectl"
  end

  test do
    assert_match /Command line interface for Alphaus/, shell_output("#{bin}/bluectl -h", 0)
  end
end
