# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bluectl < Formula
  desc "The official command line interface for Alphaus services."
  homepage "https://github.com/alphauslabs/bluectl"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/alphauslabs/bluectl/releases/download/v0.1.1/bluectl_0.1.1_darwin_amd64.tar.gz"
    sha256 "80ed8e2fe6014fc28df3b362708200dcebfd128ac3f284bcd0eff9b517f70d6a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/alphauslabs/bluectl/releases/download/v0.1.1/bluectl_0.1.1_linux_amd64.tar.gz"
    sha256 "ded524f8fbf405a79b819808dcd756d3b9a345a556dbbf20ca3986f94a038b77"
  end

  def install
    bin.install "bluectl"
  end

  test do
    assert_match /Command line interface for Alphaus/, shell_output("#{bin}/bluectl -h", 0)
  end
end
