# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bluectl < Formula
  desc "The official command line interface for Alphaus services."
  homepage "https://github.com/alphauslabs/bluectl"
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/alphauslabs/bluectl/releases/download/v0.0.6/bluectl_0.0.6_darwin_amd64.tar.gz"
    sha256 "857994d228b0d84f8cc6b4dd92afaacccb4fd04e58e840768ed83abc2aa5ed48"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/alphauslabs/bluectl/releases/download/v0.0.6/bluectl_0.0.6_linux_amd64.tar.gz"
    sha256 "f25e016be74ba5bb522cf3117c29b6a83e935f2aa822253ab67100796740982d"
  end

  def install
    bin.install "bluectl"
  end

  test do
    assert_match /Command line interface for Alphaus/, shell_output("#{bin}/bluectl -h", 0)
  end
end
