# This file was generated by GoReleaser. DO NOT EDIT.
class Ccf < Formula
  desc "Companion tool for ouchan/linkbatchd."
  homepage "https://github.com/mobingi/ouchantools"
  version "1.0.28"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.28/ouchantools_1.0.28_darwin_amd64.tar.gz"
    sha256 "43371960027193b3f4c1706b7e287be941e82c26e647acbc75aa6497cdaad0cf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mobingi/ouchantools/releases/download/v1.0.28/ouchantools_1.0.28_linux_amd64.tar.gz"
      sha256 "b778aec25876705b74d735b343bb4eb68178a67c65798e52d6f19ded1d055047"
    end
  end

  def install
    bin.install "ccf"
  end

  test do
    assert_match /Collection of internal commands/, shell_output("#{bin}/ccf -h", 0)
  end
end
