# This file was generated by GoReleaser. DO NOT EDIT.
class Linkbatchd < Formula
  desc "Batch binary for Ripple/Wave for AWS."
  homepage "https://github.com/mobingi/ouchantools"
  version "1.0.38"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.38/ouchantools_1.0.38_darwin_amd64.tar.gz"
    sha256 "5d5697759c315b012421f923ca87dfe300837443d5ee2e935eb70f1eebc5adcb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mobingi/ouchantools/releases/download/v1.0.38/ouchantools_1.0.38_linux_amd64.tar.gz"
      sha256 "910e4df754909c6c0a558ebe31c8c6df12e0e21f12d3b30ca59193ba0b9c56f2"
    end
  end

  def install
    bin.install "linkbatchd"
  end

  test do
    assert_match /Batch for link acct/, shell_output("#{bin}/linkbatchd -h", 0)
  end
end
