# This file was generated by GoReleaser. DO NOT EDIT.
class Linkbatchd < Formula
  desc "Batch binary for Ripple/Wave for AWS."
  homepage "https://github.com/mobingi/ouchantools"
  version "1.0.33"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mobingi/ouchantools/releases/download/v1.0.33/ouchantools_1.0.33_darwin_amd64.tar.gz"
    sha256 "0683c42aecfb30461248a85e3d323ed4aa29c4253b21f5ae7c95c7ef1c3a6e2e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mobingi/ouchantools/releases/download/v1.0.33/ouchantools_1.0.33_linux_amd64.tar.gz"
      sha256 "5684b4b064e11771b6588c181c6b025e6b074a47825a7b7eaecae0c5d4aea991"
    end
  end

  def install
    bin.install "linkbatchd"
  end

  test do
    assert_match /Batch for link acct/, shell_output("#{bin}/linkbatchd -h", 0)
  end
end
