# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oops < Formula
  desc "Kubernetes-native testing tool."
  homepage "https://github.com/mobingi/oops"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mobingi/oops/releases/download/v1.1.1/oops_1.1.1_darwin_amd64.tar.gz"
    sha256 "8e14a99a5101da058294be016d7de8a8407e2733e0b483d2f4cd20a63db1b43c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mobingi/oops/releases/download/v1.1.1/oops_1.1.1_linux_amd64.tar.gz"
    sha256 "76aaa25e4946551bf53f413c1530258e80d72a71503f2ffff62895b5458236e1"
  end

  def install
    bin.install "oops"
  end

  test do
    assert_match /Kubernetes-native testing tool/, shell_output("#{bin}/oops -h", 0)
  end
end
