# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oops < Formula
  desc "Kubernetes-native testing tool."
  homepage "https://github.com/mobingi/oops"
  version "1.1.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mobingi/oops/releases/download/v1.1.3/oops_1.1.3_darwin_amd64.tar.gz"
      sha256 "4869382f39c97a308a87ba3561300e0091aed6122b9ff8f901bcfcb3b837888f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mobingi/oops/releases/download/v1.1.3/oops_1.1.3_linux_amd64.tar.gz"
      sha256 "3b41e57c5ddc439c5da02f8e027d572a3dd823214f9f31a2f42bb4064d9ec225"
    end
  end

  def install
    bin.install "oops"
  end

  test do
    assert_match /Kubernetes-native testing tool/, shell_output("#{bin}/oops -h", 0)
  end
end
